### ISSUE TITLE
While klipper starts following error rises

### ISSUE THREAD

**Issue by emesys** [aamott/klipper_zoned_hotbed_macros#1]
Error loading template 'gcode_macro HEAT_BED_ZONE:gcode': jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'zone_temps'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.

**Comment by aamott** [comment]
Thanks for reporting! I finally got to put it into klipper. Haven't actually tested the macro yet, but at the least it won't prevent klipper from starting! Next up: Try it on a bunch of virtual heaters!

**Comment by aamott** [comment]
Forgot to close :)
